// GENERATED from contracts/openapi.json. Do not edit.
export const CONTRACT_VERSION = "0.3.0" as const;
export type AssumptionRecord = { "id": string; "values": Assumptions };
export type Assumptions = { "cost_exposure": string; "effective_price_shock": string; "customer_pass_through": string; "basis": "user_assumption" | "research_assumption"; "acknowledged": true; "evidence_ids"?: Array<string> };
export type Body_uploadSource = { "file": string; "url"?: string | null; "published_date"?: string | null };
export type Calculation = { "id": string; "formula_id": string; "formula_version": string; "input_fact_ids": Array<string>; "input_revisions": Record<string, number>; "assumption_snapshot": Record<string, string>; "value": string | null; "unit": "CNY" | "ratio" | "pp"; "status": "computed" | "not_computable"; "reason"?: string | null };
export type Claim = { "id": string; "kind": "fact" | "calculation" | "inference" | "opinion" | "hypothesis"; "text": string; "evidence_ids": Array<string>; "calculation_ids": Array<string>; "assumption_ids": Array<string>; "counter_evidence_ids": Array<string>; "limitations": Array<string>; "review_status": "pending" | "supported" | "insufficient" | "rejected" };
export type Dataset = { "id": string; "name": string; "company": "CATL"; "year": 2024 | 2025; "version": number; "source_ids": Array<string>; "created_at": string; "data_basis": "empty" | "reviewed_fixture" | "user_uploaded" };
export type DatasetCollection = { "items": Array<Dataset>; "next_offset": number | null };
export type DatasetCreate = { "name": string; "company": "CATL"; "year": 2024 | 2025 };
export type ErrorBody = { "code": string; "message": string; "details"?: Record<string, unknown>; "retryable": boolean; "request_id": string };
export type ErrorResponse = { "error": ErrorBody };
export type Event = { "seq": number; "run_id": string; "type": "file_access" | "tool_call" | "calculation" | "llm_call" | "node_status" | "report_generated" | "error"; "node": string; "at": string; "payload": Record<string, unknown> };
export type EventCollection = { "items": Array<Event>; "next_after_seq": number; "has_more": boolean };
export type Evidence = { "id": string; "source_id": string; "locator_kind": "pdf" | "html"; "pdf_page"?: number | null; "printed_page"?: string | null; "bbox"?: Array<number> | null; "url"?: string | null; "selector"?: string | null; "excerpt": string; "sha256": string };
export type Fact = { "id": string; "revision"?: number; "company": string; "metric": "revenue" | "cost_of_sales" | "parent_net_profit" | "parent_adjusted_net_profit" | "operating_cash_flow" | "total_assets" | "parent_equity" | "inventory" | "accounts_receivable" | "reported_gross_margin"; "segment": "group" | "power_battery" | "energy_storage"; "statement_scope": "consolidated"; "period_kind": "annual_flow" | "point_in_time"; "period_start"?: string | null; "period_end": string; "currency"?: "CNY"; "value": string | null; "unit": "CNY" | "ratio"; "raw_value": string | null; "raw_unit": "CNY_thousand" | "percent"; "status": "extracted" | "needs_review" | "verified" | "missing" | "conflict"; "evidence_ids": Array<string>; "missing_reason"?: string | null; "restatement_status"?: "not_restated" | "restated" | "unknown" };
export type FactCollection = { "dataset_id": string; "dataset_version": number; "items": Array<Fact> };
export type FactCorrection = { "expected_revision": number; "value": string | null; "raw_value"?: string | null; "status": "verified" | "missing" | "needs_review"; "evidence_ids": Array<string>; "reason": string; "missing_reason"?: string | null };
export type Report = { "run_id": string; "dataset_id": string; "dataset_version": number; "mode": "live" | "replay"; "title": string; "facts": Array<Fact>; "calculations": Array<Calculation>; "claims": Array<Claim>; "scenarios": Array<ScenarioResult>; "assumptions": Array<AssumptionRecord>; "evidence": Array<Evidence>; "limitations": Array<string>; "generated_at": string };
export type ResumeRequest = { "expected_run_status": "waiting_review"; "dataset_version": number; "assumptions"?: Assumptions | null };
export type Run = { "id": string; "dataset_id": string; "dataset_version": number; "status": "queued" | "running" | "waiting_review" | "completed" | "partial" | "failed" | "cancelled"; "mode": "live" | "replay"; "current_node": string | null; "missing_requirements": Array<string>; "stale": boolean; "error": ErrorBody | null; "report_ready": boolean };
export type RunCreate = { "dataset_id": string; "dataset_version": number; "question": string; "segment": "power_battery" | "energy_storage"; "mode": "live" | "replay"; "assumptions"?: Assumptions | null; "replay_run_id"?: string | null };
export type ScenarioBaseline = { "revenue": string; "cost_of_sales": string; "gross_profit": string; "gross_margin": string };
export type ScenarioOutputs = { "revenue": string; "cost_of_sales": string; "gross_profit": string; "gross_margin": string; "delta_gross_profit": string; "delta_gross_margin_pp": string; "delta_cost": string };
export type ScenarioRequest = { "dataset_id": string; "dataset_version": number; "revenue_fact_id": string; "cost_fact_id": string; "revenue_revision": number; "cost_revision": number; "model_version": "static-gross-profit-v1"; "assumptions": Assumptions };
export type ScenarioResult = { "scenario_id": string; "model_version": string; "dataset_id": string; "dataset_version": number; "revenue_fact_id": string; "cost_fact_id": string; "input_revisions": Record<string, number>; "assumption_id": string; "baseline": ScenarioBaseline; "assumptions": Assumptions; "outputs": ScenarioOutputs; "calculation_ids": Array<string>; "limitations": Array<string>; "mode"?: "conditional_scenario" };
export type Source = { "id": string; "filename": string; "sha256": string; "media_type": "application/pdf" | "text/csv"; "page_count"?: number | null; "url": string | null; "published_date": string | null; "parse_status": "queued" | "parsed" | "needs_review" | "failed"; "data_basis": "reviewed_fixture" | "user_uploaded" };
export type SourceAttachment = { "dataset": Dataset; "source": Source };
export type Operations = {
  health: { request: unknown; response: Blob; method: "GET"; path: "/health" };
  createDataset: { request: DatasetCreate; response: Dataset; method: "POST"; path: "/api/v1/datasets" };
  listDatasets: { request: unknown; response: DatasetCollection; method: "GET"; path: "/api/v1/datasets" };
  getDataset: { request: unknown; response: Dataset; method: "GET"; path: "/api/v1/datasets/{id}" };
  uploadSource: { request: unknown; response: SourceAttachment; method: "POST"; path: "/api/v1/datasets/{id}/sources" };
  listFacts: { request: unknown; response: FactCollection; method: "GET"; path: "/api/v1/datasets/{id}/facts" };
  correctFact: { request: FactCorrection; response: Fact; method: "PATCH"; path: "/api/v1/facts/{id}" };
  createRun: { request: RunCreate; response: Run; method: "POST"; path: "/api/v1/runs" };
  getRun: { request: unknown; response: Run; method: "GET"; path: "/api/v1/runs/{id}" };
  getRunEvents: { request: unknown; response: EventCollection; method: "GET"; path: "/api/v1/runs/{id}/events" };
  resumeRun: { request: ResumeRequest; response: Run; method: "POST"; path: "/api/v1/runs/{id}/resume" };
  createScenario: { request: ScenarioRequest; response: ScenarioResult; method: "POST"; path: "/api/v1/scenarios" };
  getEvidence: { request: unknown; response: Evidence; method: "GET"; path: "/api/v1/evidence/{id}" };
  getCalculation: { request: unknown; response: Calculation; method: "GET"; path: "/api/v1/calculations/{id}" };
  getSource: { request: unknown; response: Source; method: "GET"; path: "/api/v1/sources/{id}" };
  getSourceContent: { request: unknown; response: Blob; method: "GET"; path: "/api/v1/sources/{id}/content" };
  getReport: { request: unknown; response: Report; method: "GET"; path: "/api/v1/runs/{id}/report" };
};
